-- Generated by Oracle SQL Developer Data Modeler 17.4.0.355.2131
--   at:        2018-04-20 19:30:11 SGT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g
-- author: Loi Chai Lam
--student id: 2813 6179

SET ECHO ON

SPOOL monlib_schema_output.txt

DROP SEQUENCE author_aucode_seq;

DROP SEQUENCE borrower_borrno_seq;

DROP SEQUENCE branch_brancode_seq;

DROP SEQUENCE seq_manno;

DROP SEQUENCE publisher_pubcode_seq;

DROP TABLE author CASCADE CONSTRAINTS;

DROP TABLE book CASCADE CONSTRAINTS;

DROP TABLE bookauthor CASCADE CONSTRAINTS;

DROP TABLE booksubject CASCADE CONSTRAINTS;

DROP TABLE borrclassification CASCADE CONSTRAINTS;

DROP TABLE borrower CASCADE CONSTRAINTS;

DROP TABLE branch CASCADE CONSTRAINTS;

DROP TABLE copies CASCADE CONSTRAINTS;

DROP TABLE fine CASCADE CONSTRAINTS;

DROP TABLE isbn CASCADE CONSTRAINTS;

DROP TABLE loan CASCADE CONSTRAINTS;

DROP TABLE manager CASCADE CONSTRAINTS;

DROP TABLE publisher CASCADE CONSTRAINTS;

DROP TABLE reservation CASCADE CONSTRAINTS;

DROP TABLE subject CASCADE CONSTRAINTS;

CREATE TABLE author (
    aucode   NUMBER(7) NOT NULL,
    auname   VARCHAR2(20) NOT NULL
);

COMMENT ON COLUMN author.aucode IS
    'The author''s code';

COMMENT ON COLUMN author.auname IS
    'The author''s name';

ALTER TABLE author ADD CONSTRAINT author_pk PRIMARY KEY ( aucode );

CREATE TABLE book (
    bookcallno           VARCHAR2(20) NOT NULL,
    booktitle            VARCHAR2(100) NOT NULL,
    bookdescription      VARCHAR2(1000) NOT NULL,
    bookpubyear          NUMBER(4) NOT NULL,
    bookprice            NUMBER(6,2) NOT NULL,
    booknumberpages      NUMBER(5) NOT NULL,
    bookclassification   VARCHAR2(10) NOT NULL,
    bookreadinglevel     NUMBER(2),
    pubcode              NUMBER(7) NOT NULL
);

ALTER TABLE book ADD CONSTRAINT chk_bookprice CHECK ( bookprice > 0 );

ALTER TABLE book ADD CONSTRAINT chk_booknumberpages CHECK ( booknumberpages > 0 );

ALTER TABLE book
    ADD CONSTRAINT chk_bookreadinglevel CHECK ( bookreadinglevel BETWEEN 1 AND 30 );

COMMENT ON COLUMN book.bookcallno IS
    'The Dewey Decimal call no of a book';

COMMENT ON COLUMN book.booktitle IS
    'The title of the book';

COMMENT ON COLUMN book.bookdescription IS
    'The description of the book';

COMMENT ON COLUMN book.bookpubyear IS
    'The publication year of book';

COMMENT ON COLUMN book.bookprice IS
    'The price of book';

COMMENT ON COLUMN book.booknumberpages IS
    'The total number of pages of a book';

COMMENT ON COLUMN book.bookclassification IS
    'The classification of a  book (Reference or Fiction)';

COMMENT ON COLUMN book.bookreadinglevel IS
    'For a Fiction title, the reading level of the book';

COMMENT ON COLUMN book.pubcode IS
    'The publisher''s code';

ALTER TABLE book ADD CONSTRAINT book_pk PRIMARY KEY ( bookcallno );

CREATE TABLE bookauthor (
    bookcallno   VARCHAR2(20) NOT NULL,
    aucode       NUMBER(7) NOT NULL
);

COMMENT ON COLUMN bookauthor.bookcallno IS
    'The Dewey Decimal call no of a book';

COMMENT ON COLUMN bookauthor.aucode IS
    'The author''s code';

ALTER TABLE bookauthor ADD CONSTRAINT bookauthor_pk PRIMARY KEY ( bookcallno,
aucode );

CREATE TABLE booksubject (
    bookcallno   VARCHAR2(20) NOT NULL,
    subname      VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN booksubject.bookcallno IS
    'The Dewey Decimal call no of a book';

COMMENT ON COLUMN booksubject.subname IS
    'The subject name of the book';

ALTER TABLE booksubject ADD CONSTRAINT booksubject_pk PRIMARY KEY ( bookcallno,
subname );

CREATE TABLE borrclassification (
    borrclass       VARCHAR2(15) NOT NULL,
    numberofbooks   NUMBER(3) NOT NULL,
    loanperiod      NUMBER(3) NOT NULL
);

ALTER TABLE borrclassification ADD CONSTRAINT chk_numberofbooks CHECK ( numberofbooks > 0 );

ALTER TABLE borrclassification ADD CONSTRAINT chk_loanperiod CHECK ( loanperiod > 0 );

COMMENT ON COLUMN borrclassification.borrclass IS
    'The classification of borrower(Junior, Adult, Organisation)';

COMMENT ON COLUMN borrclassification.numberofbooks IS
    'The restriction on the number of books a borrower may have on loan at any one time.'
;

COMMENT ON COLUMN borrclassification.loanperiod IS
    'The loan period of the borrower classification';

ALTER TABLE borrclassification ADD CONSTRAINT borrclassification_pk PRIMARY KEY ( borrclass
);

CREATE TABLE borrower (
    borrno        NUMBER(7) NOT NULL,
    borrname      VARCHAR2(50) NOT NULL,
    borraddress   VARCHAR2(50) NOT NULL,
    borrflag      CHAR(1) NOT NULL,
    borrclass     VARCHAR2(15) NOT NULL,
    brancode      NUMBER(3) NOT NULL
);

COMMENT ON COLUMN borrower.borrno IS
    'The borrower id number';

COMMENT ON COLUMN borrower.borrname IS
    'The name of the borrower';

COMMENT ON COLUMN borrower.borraddress IS
    'The address of the borrower';

COMMENT ON COLUMN borrower.borrflag IS
    'The status of borrower to determine he/she can borrow a book or not';

COMMENT ON COLUMN borrower.borrclass IS
    'The classification of borrower(Junior, Adult, Organisation)';

COMMENT ON COLUMN borrower.brancode IS
    'The code of the branch';

ALTER TABLE borrower ADD CONSTRAINT borrower_pk PRIMARY KEY ( borrno );

CREATE TABLE branch (
    brancode      NUMBER(3) NOT NULL,
    branname      VARCHAR2(50) NOT NULL,
    branaddress   VARCHAR2(50) NOT NULL,
    branphone     CHAR(10) NOT NULL,
    manno         NUMBER(7) NOT NULL
);

ALTER TABLE branch ADD CONSTRAINT chk_brancode CHECK ( brancode >= 100 );

COMMENT ON COLUMN branch.brancode IS
    'The code of the branch';

COMMENT ON COLUMN branch.branname IS
    'The name of the branch';

COMMENT ON COLUMN branch.branaddress IS
    'The address of the branch';

COMMENT ON COLUMN branch.branphone IS
    'The phone number of the branch';

COMMENT ON COLUMN branch.manno IS
    'The id of manager.';

ALTER TABLE branch ADD CONSTRAINT branch_pk PRIMARY KEY ( brancode );

CREATE TABLE copies (
    copybarcodeno   NUMBER(15) NOT NULL,
    statusflag      CHAR(1) NOT NULL,
    bookcallno      VARCHAR2(20) NOT NULL,
    brancode        NUMBER(3) NOT NULL
);

COMMENT ON COLUMN copies.copybarcodeno IS
    'The barcode number of the copies';

COMMENT ON COLUMN copies.statusflag IS
    'The flag of the copies to indicate if it is on counter reserve or not';

COMMENT ON COLUMN copies.bookcallno IS
    'The Dewey Decimal call no of a book';

COMMENT ON COLUMN copies.brancode IS
    'The code of the branch';

ALTER TABLE copies ADD CONSTRAINT copies_pk PRIMARY KEY ( copybarcodeno );

CREATE TABLE fine (
    copybarcodeno     NUMBER(15) NOT NULL,
    borrno            NUMBER(7) NOT NULL,
    loanreturndate    DATE NOT NULL,
    finepaymentdate   DATE,
    fineamount        NUMBER(6,2) NOT NULL
);

ALTER TABLE fine ADD CONSTRAINT chk_fineamount CHECK ( fineamount > 0 );

COMMENT ON COLUMN fine.copybarcodeno IS
    'The barcode number of the copies';

COMMENT ON COLUMN fine.borrno IS
    'The borrower id number';

COMMENT ON COLUMN fine.loanreturndate IS
    'The return date of the loan';

COMMENT ON COLUMN fine.finepaymentdate IS
    'The payment date when the borrower pay the fine';

COMMENT ON COLUMN fine.fineamount IS
    'The fine amount';

ALTER TABLE fine
    ADD CONSTRAINT fine_pk PRIMARY KEY ( copybarcodeno,
    borrno,
    loanreturndate );

CREATE TABLE isbn (
    isbncode     VARCHAR2(50) NOT NULL,
    bookcallno   VARCHAR2(20) NOT NULL
);

COMMENT ON COLUMN isbn.isbncode IS
    'The ISBN code of the book';

COMMENT ON COLUMN isbn.bookcallno IS
    'The Dewey Decimal call no of a book';

ALTER TABLE isbn ADD CONSTRAINT isbn_pk PRIMARY KEY ( isbncode );

CREATE TABLE loan (
    copybarcodeno          NUMBER(15) NOT NULL,
    loanreturndate         DATE NOT NULL,
    borrno                 NUMBER(7) NOT NULL,
    loanactualreturndate   DATE
);

COMMENT ON COLUMN loan.copybarcodeno IS
    'The barcode number of the copies';

COMMENT ON COLUMN loan.loanreturndate IS
    'The return date of the loan';

COMMENT ON COLUMN loan.borrno IS
    'The borrower id number';

COMMENT ON COLUMN loan.loanactualreturndate IS
    'The actual return date of the book';

ALTER TABLE loan
    ADD CONSTRAINT loan_pk PRIMARY KEY ( copybarcodeno,
    borrno,
    loanreturndate );

CREATE TABLE manager (
    manno      NUMBER(7) NOT NULL,
    manname    VARCHAR2(50) NOT NULL,
    manphone   CHAR(10) NOT NULL,
    brancode   NUMBER(3) NOT NULL
);

COMMENT ON COLUMN manager.manno IS
    'The id of manager.';

COMMENT ON COLUMN manager.manname IS
    'The manager''s name';

COMMENT ON COLUMN manager.manphone IS
    'The manager''s phone number';

COMMENT ON COLUMN manager.brancode IS
    'The code of the branch';

ALTER TABLE manager ADD CONSTRAINT manager_pk PRIMARY KEY ( manno );

CREATE TABLE publisher (
    pubcode   NUMBER(7) NOT NULL,
    pubname   VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN publisher.pubcode IS
    'The publisher''s code';

COMMENT ON COLUMN publisher.pubname IS
    'The publisher''s name';

ALTER TABLE publisher ADD CONSTRAINT publisher_pk PRIMARY KEY ( pubcode );

CREATE TABLE reservation (
    resdate         DATE NOT NULL,
    copybarcodeno   NUMBER(15) NOT NULL,
    borrno          NUMBER(7) NOT NULL
);

COMMENT ON COLUMN reservation.resdate IS
    'The reservation date';

COMMENT ON COLUMN reservation.copybarcodeno IS
    'The barcode number of the copies';

COMMENT ON COLUMN reservation.borrno IS
    'The borrower id number';

ALTER TABLE reservation
    ADD CONSTRAINT reservation_pk PRIMARY KEY ( copybarcodeno,
    resdate,
    borrno );

CREATE TABLE subject (
    subname   VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN subject.subname IS
    'The subject name of the book';

ALTER TABLE subject ADD CONSTRAINT subject_pk PRIMARY KEY ( subname );

ALTER TABLE book
    ADD CONSTRAINT book_publisher_fk FOREIGN KEY ( pubcode )
        REFERENCES publisher ( pubcode );

ALTER TABLE bookauthor
    ADD CONSTRAINT bookauthor_author_fk FOREIGN KEY ( aucode )
        REFERENCES author ( aucode );

ALTER TABLE bookauthor
    ADD CONSTRAINT bookauthor_book_fk FOREIGN KEY ( bookcallno )
        REFERENCES book ( bookcallno );

ALTER TABLE booksubject
    ADD CONSTRAINT booksubject_book_fk FOREIGN KEY ( bookcallno )
        REFERENCES book ( bookcallno );

ALTER TABLE booksubject
    ADD CONSTRAINT booksubject_subject_fk FOREIGN KEY ( subname )
        REFERENCES subject ( subname );

ALTER TABLE borrower
    ADD CONSTRAINT borrower_borrclassification_fk FOREIGN KEY ( borrclass )
        REFERENCES borrclassification ( borrclass )
            ON DELETE CASCADE;

ALTER TABLE borrower
    ADD CONSTRAINT borrower_branch_fk FOREIGN KEY ( brancode )
        REFERENCES branch ( brancode );

ALTER TABLE branch
    ADD CONSTRAINT branch_manager_fk FOREIGN KEY ( manno )
        REFERENCES manager ( manno );

ALTER TABLE copies
    ADD CONSTRAINT copies_book_fk FOREIGN KEY ( bookcallno )
        REFERENCES book ( bookcallno );

ALTER TABLE copies
    ADD CONSTRAINT copies_branch_fk FOREIGN KEY ( brancode )
        REFERENCES branch ( brancode );

ALTER TABLE fine
    ADD CONSTRAINT fine_loan_fk FOREIGN KEY ( copybarcodeno,
    borrno,
    loanreturndate )
        REFERENCES loan ( copybarcodeno,
        borrno,
        loanreturndate );

ALTER TABLE isbn
    ADD CONSTRAINT isbn_book_fk FOREIGN KEY ( bookcallno )
        REFERENCES book ( bookcallno )
            ON DELETE CASCADE;

ALTER TABLE loan
    ADD CONSTRAINT loan_borrower_fk FOREIGN KEY ( borrno )
        REFERENCES borrower ( borrno );

ALTER TABLE loan
    ADD CONSTRAINT loan_copies_fk FOREIGN KEY ( copybarcodeno )
        REFERENCES copies ( copybarcodeno );

ALTER TABLE manager
    ADD CONSTRAINT manager_branch_fk FOREIGN KEY ( brancode )
        REFERENCES branch ( brancode );

ALTER TABLE reservation
    ADD CONSTRAINT reservation_borrower_fk FOREIGN KEY ( borrno )
        REFERENCES borrower ( borrno )
            ON DELETE CASCADE;

ALTER TABLE reservation
    ADD CONSTRAINT reservation_copies_fk FOREIGN KEY ( copybarcodeno )
        REFERENCES copies ( copybarcodeno )
            ON DELETE CASCADE;

CREATE SEQUENCE author_aucode_seq START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE borrower_borrno_seq START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE branch_brancode_seq START WITH 100 NOCACHE ORDER;

CREATE SEQUENCE seq_manno START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE publisher_pubcode_seq START WITH 1 NOCACHE ORDER;

SET ECHO OFF

SPOOL OFF

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            15
-- CREATE INDEX                             0
-- ALTER TABLE                             39
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          5
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
